### ISSUE TITLE
driver에서 ```jsStopped``` state 존재 시 동작 문의

### ISSUE THREAD

**Issue by ygr4789** [SNU-ARC/2024_spring_sysprog_Lab4#12]
```trace09.txt``` testcase에 대해, make rtest09와 make test09 동작이 달라 문의드립니다.

```trace09.txt```  는 다음과 같이 foreground에 myspin 실행 수 stop signal을 보내는데,
```
#
# trace09.txt - Forward SIGTSTP only to foreground job.
#
/bin/echo -e "csapsh> ./myspin 4 \046"
./myspin 4 &

/bin/echo -e "csapsh> ./myspin 5"
./myspin 5 

SLEEP 2.5
TSTP

/bin/echo "csapsh> jobs"
jobs

```

make rtest09의 경우 EOF를 받고 쉘이 종료하나 make test09는 종료하지 않는 현상이 발생합니다.

**Comment by yunjayh** [comment]
현재 제공해주신 부분만으로는 현상의 원인을 알기 어렵습니다.
마침 내일 보강 수업이 있으니, 수업 종료 후 짧은 시간 확인 도와드릴 수 있을 것 같습니다.
만약 보강에 오신다면 빠른 피드백을 위해 현재 구현을 조교 메일로 보내주세요.
그 외의 방법으로는 구현의 세부 내용을 피드백 하기 어려운 점 양해 부탁드립니다.

**Comment by ygr4789** [comment]
waitfg 구현 오류로 쉘이 종료되지 않는 문제였습니다, 해결하였습니다.
