### ISSUE TITLE
TRACE file 관련 질문이 있습니다.

### ISSUE THREAD

**Issue by hojoonleokim** [SNU-ARC/2024_spring_sysprog_Lab4#18]
안녕하세요
제 코드를 TRACE025 파일에 실행했을 때
`ps -eo stat,command | grep ./mysplit`
command에 대한 결과가 실행할때마다 다르게 나옵니다.
혹시 제 코드의 문제일까요?

-----setpgid 설정시에 오류가 나서 foreground process group에 남아있는것이 원인이었는데 함수 실행 순서들을 바꿔보니 해결이 되었습니다.

<img width="500" alt="Screenshot 2024-06-01 at 11 13 30 AM" src="https://github.com/SNU-ARC/2024_spring_sysprog_Lab4/assets/81799917/6a4eda6f-540f-47f8-a804-90c5d990dec7">

Q2. 그리고 혹시 랩 시간에 ref 12-14만 다를 수 있다고 하신 것으로 기억하는데 맞을까요?

-----해결하였습니다!

감사합니다!!

**Comment by k296070** [comment]
해결하였습니다!

**Comment by k296070** [comment]
해결하였습니다!

**Comment by k296070** [comment]
그리고 혹시 랩 시간에 ref 12-14만 다를 수 있다고 하신 것으로 기억하는데 맞을까요?

**Comment by k296070** [comment]
S/S+가 나오는 문제는 일정하게 출력하도록 해결하였습니다!!
