### ISSUE TITLE
trace25의 timing 관련 이슈 질문드립니다

### ISSUE THREAD

**Issue by AutoclickerI** [SNU-ARC/2024_spring_sysprog_Lab4#23]
![image](https://github.com/SNU-ARC/2024_spring_sysprog_Lab4/assets/87906440/6f655c56-5a17-403e-bbdc-6e93caab12f4)
Readme의 조건에 보면, 하나의 job에서 process들은 모두 하나의 process group에 속해야 한다고 이해했습니다.
이를 보장하기 위해, 각 job에서 첫 번째 child는 자기 자신의 pid를 pgid로, 2번째~마지막까지의 child는 각 job의 첫 번째 child의 pid를 pgid로 가져야 한다고 생각했습니다. 즉,

tools/myspin 10 | tools/mychild 10
을 실행한 후, Ctrl+C를 누르면 두개의 프로세스가 모두 종료되어야 합니다.

하지만 fork()를 실행한 경우, 각 프로세스는 fork한 순서대로 스케줄링 된다는 보장이 없으며, 이를 해결하기 위해 하나의 job에서 while문을 이용하여 wait을 구현해 sync가 맞도록 구현해 주었습니다.

이렇게 sync를 맞추니 trace25에서 문제가 발생하였습니다.
![image](https://github.com/SNU-ARC/2024_spring_sysprog_Lab4/assets/87906440/3ac42363-ecae-4dcd-a936-020bd65946e9)

ps -eo stat,command | grep ./mysplit
라는 명령에서, grep ./mysplit이 실행된 이후 ps -eo stat,command에 "grep ./mysplit"이라는 명령이 스캔되고, 그 후 스캔된 output을 pipe로 받아와서 grep를 진행해야 합니다.
이때 sync를 맞추기 위해 ps -eo stat,command의 pgid가 자기 자신으로 세팅된 것을 "grep ./mysplit"이 기다린 후, pgid를 세팅해 준 다음 execv로 "grep ./mysplit"을 실행시켜 주어야 하는데 그 과정에서 시간이 소요되어 grep가 실제로 실행되기 전에 ps -eo stat,command가 실행이 끝나 cat file2에 아무것도 입력되지 않게 되었습니다.

Readme의 조건(process group를 한번에 제어할 수 있어야 함)을 지키지 않고 무조건 child에서 setpgid(0,0)을 해 주어도 trace를 모두 통과하는데는 지장이 없으나, 이 경우 위에서 언급한 "tools/myspin 10 | tools/mychild 10"라는 예제를 통과하지 못하게 되는데, 이 경우 어떻게 해결해야 하는지 문의드립니다.

다른 환경에서는 작동이 보장되지 않으나, "수업 시간에 제공된 VirtualBox 환경에서만 정상적으로 돌아갈 확률이 높은"코드를 제출하여도 채점에 문제가 없을까요?

**Comment by yunjayh** [comment]
> ps -eo stat,command의 pgid가 자기 자신으로 세팅된 것을 "grep ./mysplit"이 기다린 후, pgid를 세팅해 준 다음 execv로 "grep ./mysplit"을 실행시켜 주어야 하는데

child process의 pgid에 대한 timing issue로 인한 race condition은 항상 발생할 수 있는 중요한 사항입니다. 학생분께서는 이를 방지하기 위한 해결책으로 일종의 busy waiting을 구현하신 것으로 이해됩니다. 
이를 다른 방식으로 접근하여 매 child process 생성에 대해 pgid를 올바르게 세팅해준다면 제기해주신 문제가 해결 될 수 있을 것입니다.

> 다른 환경에서는 작동이 보장되지 않으나, "수업 시간에 제공된 VirtualBox 환경에서만 정상적으로 돌아갈 확률이 높은"코드를 제출하여도 채점에 문제가 없을까요?

바람직한 해결 방법은 아니지만, 기존에 언급되었던 것 처럼, 채점은 제공된 trace들의 실행에 대해서만 진행됩니다. 조교로써는 위의 답변을 토대로 해당 문제를 풀어보시는 것을 추천드리고, 과제에서 겪은 어려웠던 부분을 보고서에 담으시는 것이 도움될 수 있을 것 같습니다. 

혹시라도 추가적인 답변이 있을경우 아래에 더하여 답변 드리겠습니다.

**Comment by VioletXF** [comment]
안녕하세요 조교님, reference csapsh의 경우에도 file2의 내용이 `R grep ./mysplit` | `S grep ./mysplit` | `<empty>`로 총 3가지로 나오는데, reference 구현도 timing issue를 제대로 처리하지 않고 있다고 보면 될까요?

**Comment by yunjayh** [comment]
네 cmd가 순차적으로 fork 되지만 실행 순서는 보장되지 않는 특성상 언급하신 세가지 output이 모두 생성될 수 있습니다. `reference/rtest25.out`에서 해당 라인은 세 출력 모두 가능한 출력으로 두고 채점될 예정입니다. 
위의 답변은 학생의 구현 예시에서 다른 output이 나오지 않고, `<empty>`로만 출력된다고 이해되어 언급한 부분을 신경쓴다면 reference와 같은 출력을 얻을 수 있을것으로 기대됨을 전달드렸습니다.
